name: CI Selenium

on:
  push:
    branches:
      - main

jobs:
  deploy-aut:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker
        run: docker build -t aut-app .

      - name: Run Container
        run: docker run -d -p 8080:80 aut-app

      - name: Wait for server
        run: sleep 10

      - name: Test URL
        run: curl http://localhost:8080

